layout_spectrum: 0.6815252
color:
  saturation: 0.6342642
  brandStrength: 0.480666
  lightness: 0.3754028
  brandColors:
    - '#FFFFFF'
    - '#006893'
    - '#030303'
    - '#94BFD1'
    - '#5C9EBA'
  rhythmicContrast: 0.5644469
typography_spectrum: 0.4065521
name: adventura foundation
