collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
typography_spectrum: 0.4065521
color:
  saturation: 0
  brandStrength: 0.480666
  lightness: 0
  brandColors:
    - '#FFFFFF'
    - '#006893'
    - '#030303'
    - '#94BFD1'
    - '#5C9EBA'
  rhythmicContrast: 0.2400644
layout_spectrum: 0.6815252
name: adventura foundation
