layout_spectrum: 0.6815252
typography_spectrum: 0.4065521
color:
  saturation: 0.3088832
  lightness: 0.655076
  brandStrength: 0.693307
  rhythmicContrast: 0.7150096
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
name: adventura foundation
