layout_spectrum: 0.6815252
typography_spectrum: 0.4065521
color:
  saturation: 0.4473684
  brandStrength: 0.480666
  lightness: 0.1015037
  brandColors:
    - '#FFFFFF'
    - '#006893'
    - '#030303'
    - '#94BFD1'
    - '#5C9EBA'
  rhythmicContrast: 0.5644469
name: adventura foundation
